import RootLayout, { metadata } from "./layout";

describe("RootLayout", () => {
  it("returns html/body structure with expected language and classes", () => {
    const child = <main>Dashboard child content</main>;
    const layoutElement = RootLayout({ children: child });

    expect(layoutElement.type).toBe("html");
    expect(layoutElement.props.lang).toBe("en");

    const bodyElement = layoutElement.props.children;
    expect(bodyElement.type).toBe("body");
    expect(bodyElement.props.className).toContain("geist-sans");
    expect(bodyElement.props.className).toContain("geist-mono");
    expect(bodyElement.props.className).toContain("antialiased");
    expect(bodyElement.props.children).toBe(child);
  });
});

describe("layout metadata", () => {
  it("exports the expected default metadata", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});
